### ISSUE TITLE
Problems with Python3.7

### ISSUE THREAD

**Issue by unrealfuzzy** [briancappello/flask-react-spa#16]
Hi, I need to use Python3.7 with this boilerplate but I been getting these errors when I update from 3.6 to 3.7:

```
flask-react-spa: python3 manage.py db upgrade
Traceback (most recent call last):
  File "/Users/.../flask-react-spa/backend/magic.py", line 331, in models
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 62, in <module>
    main()
  File "manage.py", line 58, in main
    cli.main(args=sys.argv[1:])
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/flask/cli.py", line 515, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/flask/cli.py", line 367, in load_app
    app = call_factory(self, self.create_app)
  File "/Users/.../flask-react-spa/env/lib/python3.7/site-packages/flask/cli.py", line 114, in call_factory
    return app_factory(script_info)
  File "manage.py", line 34, in <lambda>
    create_app=lambda _: create_app(),
  File "/Users/.../flask-react-spa/backend/app.py", line 49, in create_app
    static_url_path=STATIC_URL_PATH
  File "/Users/.../flask-react-spa/backend/app.py", line 69, in _create_app
    register_models(app)
  File "/Users/.../flask-react-spa/backend/app.py", line 139, in register_models
      for model_name, model_class in bundle.models:
RuntimeError: generator raised StopIteration
```

It happens in this method:

```
def register_models(app):
    """Register bundle models."""
    models = {}
    for bundle in app.bundles:
        for model_name, model_class in bundle.models:
            models[model_name] = model_class
    app.models = models
```

Some quick Googling shows this:

```
PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)
```

Any ideas how to fix this?

**Comment by briancappello** [comment]
I believe you can replace the `raise StopIteration` calls with `return ()` ?

**Comment by unrealfuzzy** [comment]
I don't really understand what calls `raise StopIteration`. Seems like it's some internal Flask module.

**Comment by briancappello** [comment]
If you look at the top of the traceback, it says line 331 in backend/magic.py (but there are other cases too; best to do a search and replace across the code base)

**Comment by unrealfuzzy** [comment]
Yeah I just handled the iterator conversion into lists and it worked okay.
