### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'admin_base_template' is undefined

### ISSUE THREAD

**Issue by morewater** [briancappello/flask-react-spa#22]
Hi ,all 
    Anyone got this error?  It's very wired .
I also checkout the project again and rebuild it , it's still same.
I only change the database connection string to my mssql server.
Is a database connect issue ?   Or configuration issue ?

stacktrace here 

> `Traceback (most recent call last):
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/morewater/Documents/workspace/eplating/invoice/backend/security/views/login.py", line 36, in login
    **_ctx('login'))
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask_security/core.py", line 528, in render_template
    return render_template(*args, **kwargs)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/morewater/Documents/workspace/eplating/invoice/backend/security/views/templates/security/login_user.html", line 5, in top-level template code
    {% include "security/_messages.html" %}
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/morewater/Documents/workspace/eplating/invoice/backend/security/views/templates/security/login_user.html", line 30, in root
    
  File "/Users/morewater/Documents/workspace/eplating/invoice/backend/admin/views/templates/admin/master.html", line 13, in root
    <div class="container">
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    return loader.get_source(environment, template)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "/Users/morewater/pyenv/invoice/lib/python3.7/site-packages/jinja2/loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
jinja2.exceptions.UndefinedError: 'admin_base_template' is undefined

**Comment by morewater** [comment]
need point to path /admin  then login page success
