### ISSUE TITLE
docker-compose up --build fails with permision errors

### ISSUE THREAD

**Issue by scollar71** [briancappello/flask-react-spa#9]
Actually throwing all kind of errors any help would be greatly appreciated the project looks awesome!

Errors

Attaching to flask-react-spa_redis_1, flask-react-spa_celery_beat_1, flask-react-spa_sphinx_docs_1, flask-react-spa_mailhog_1, flask-react-spa_postgres_1, flask-react-spa_celery_worker_1, flask-react-spa_backend_1, flask-react-spa_frontend_1
redis_1          | find: .: Permission denied
redis_1          | chown: .: Permission denied
celery_beat_1    | Traceback (most recent call last):
celery_beat_1    |   File "/usr/local/bin/celery", line 11, in <module>
celery_beat_1    |     sys.exit(main())
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_beat_1    |     _main()
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_beat_1    |     cmd.execute_from_commandline(argv)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celery_beat_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
celery_beat_1    |     argv = self.setup_app_from_commandline(argv)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
celery_beat_1    |     self.app = self.find_app(app)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
celery_beat_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
celery_beat_1    |     sym = symbol_by_name(app, imp=imp)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
celery_beat_1    |     return imports.symbol_by_name(name, imp=imp)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery_beat_1    |     module = imp(module_name, package=package, **kwargs)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
celery_beat_1    |     return imp(module, package=package)
celery_beat_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_beat_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
celery_beat_1    | ModuleNotFoundError: No module named 'wsgi'
flask-react-spa_redis_1 exited with code 1
flask-react-spa_celery_beat_1 exited with code 1
...
...
frontend_1       | WARNING: config.js not found, using default
frontend_1       | cp: can't stat 'frontend/app/config.js': Permission denied
frontend_1       | npm info it worked if it ends with ok
frontend_1       | npm info using npm@5.3.0
frontend_1       | npm info using node@v8.6.0
frontend_1       | npm info lifecycle frontend@0.0.1~prebuild:dll: frontend@0.0.1
frontend_1       | npm info lifecycle frontend@0.0.1~build:dll: frontend@0.0.1
frontend_1       | 
frontend_1       | > frontend@0.0.1 build:dll /flask
frontend_1       | > node frontend/internals/scripts/dependencies.js
frontend_1       | 
frontend_1       | module.js:473
frontend_1       |       throw err;
frontend_1       |       ^
frontend_1       | 
frontend_1       | Error: Cannot find module '/flask/frontend/internals/scripts/dependencies.js'
frontend_1       |     at Function.Module._resolveFilename (module.js:527:15)
frontend_1       |     at Function.Module._load (module.js:453:25)
frontend_1       |     at Function.Module.runMain (module.js:665:10)
frontend_1       |     at startup (bootstrap_node.js:187:16)
frontend_1       |     at bootstrap_node.js:607:3
frontend_1       | npm info lifecycle frontend@0.0.1~build:dll: Failed to exec build:dll script
frontend_1       | npm ERR! code ELIFECYCLE
frontend_1       | npm ERR! errno 1
frontend_1       | npm ERR! frontend@0.0.1 build:dll: `node frontend/internals/scripts/dependencies.js`
frontend_1       | npm ERR! Exit status 1
frontend_1       | npm ERR! 
frontend_1       | npm ERR! Failed at the frontend@0.0.1 build:dll script.
frontend_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1       | 
frontend_1       | npm ERR! A complete log of this run can be found in:
frontend_1       | npm ERR!     /root/.npm/_logs/2019-05-13T17_11_53_370Z-debug.log
frontend_1       | npm info it worked if it ends with ok
frontend_1       | npm info using npm@5.3.0
frontend_1       | npm info using node@v8.6.0
frontend_1       | npm info lifecycle frontend@0.0.1~prestart: frontend@0.0.1
frontend_1       | npm info lifecycle frontend@0.0.1~start: frontend@0.0.1
frontend_1       | 
frontend_1       | > frontend@0.0.1 start /flask
frontend_1       | > node frontend/server
frontend_1       | 
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
frontend_1       | module.js:473
frontend_1       |       throw err;
frontend_1       |       ^
frontend_1       | 
frontend_1       | Error: Cannot find module '/flask/frontend/server'
frontend_1       |     at Function.Module._resolveFilename (module.js:527:15)
frontend_1       |     at Function.Module._load (module.js:453:25)
frontend_1       |     at Function.Module.runMain (module.js:665:10)
frontend_1       |     at startup (bootstrap_node.js:187:16)
frontend_1       |     at bootstrap_node.js:607:3
frontend_1       | npm info lifecycle frontend@0.0.1~start: Failed to exec start script
frontend_1       | npm ERR! code ELIFECYCLE
frontend_1       | npm ERR! errno 1
frontend_1       | npm ERR! frontend@0.0.1 start: `node frontend/server`
frontend_1       | npm ERR! Exit status 1
frontend_1       | npm ERR! 
frontend_1       | npm ERR! Failed at the frontend@0.0.1 start script.
frontend_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1       | 
frontend_1       | npm ERR! A complete log of this run can be found in:
frontend_1       | npm ERR!     /root/.npm/_logs/2019-05-13T17_11_53_943Z-debug.log
flask-react-spa_frontend_1 exited with code 1
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...
backend_1        | python3: can't open file 'manage.py': [Errno 13] Permission denied
backend_1        | Waiting for postgres ready...

infinite loop or so it seems

Got Anything?

BTW 
System Info
Fedora30
kernel
5.0.13-300.fc30.x86_64

Thanks

**Comment by briancappello** [comment]
Hmm, let me take a look after work.

**Comment by briancappello** [comment]
@scollar71 Hey, so I tried doing a clean build of this from master, and it does work for me (Arch Linux). So I suspect the permissions problem is on your end?

Are you running `docker/docker-compose` as root? When I set docker up for dev I usually follow this guide: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by scollar71** [comment]
I have tried
 running all ways possible ( I think )

**Comment by scollar71** [comment]
That guide is more or less it seems how I have set-up for build

**Comment by scollar71** [comment]
Can you explain further your backend: config.js & frontend: config.py not really familiar with this type of set-up, possibly something I am doing wrong there by leaving untouched? - Other than name change naturally

**Comment by scollar71** [comment]
Unfortunately this is my only dedicated dev machine, possibly a Fedora30 issue I'm going to roll-back have another crack at it. I have had some bizarre issues since recent release of thirty. just tried local  building this with err s  as well

**Comment by scollar71** [comment]
Ok well Built Flawlessly Both local and Docker on Opensuse & Fedora29. Now I'm going to enjoy 'Tinkering' with it a little Thanks

**Comment by bsord** [comment]
Also running into this with on fresh ubuntu 20.14 install. I installed docker.io via apt-get, created docker group. added user to docker group. Only the containers which do not mount the entrypoint files fail, and with permission errors during build process. Running docker/compose as the user that's in the docker group.

**Comment by bsord** [comment]
Actually, I think I found the problem. Submitting PR later today with the changes.
